# Generated by Django 5.0.3 on 2024-03-14 09:07

import places.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_image_img_alter_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to=places.models.get_upload_path),
        ),
    ]
