# Generated by Django 5.0.3 on 2024-03-26 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_image_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
