# Generated by Django 5.0.3 on 2024-04-08 14:02

import django.db.models.deletion
import places.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to=places.models.get_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Номер изображения'),
        ),
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='Название экскурсии'),
        ),
    ]
