# Generated by Django 5.0.3 on 2024-04-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_image_img_alter_image_order_alter_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Номер изображения'),
        ),
    ]
