# Generated by Django 5.0.3 on 2024-04-22 20:12

from django.db import migrations


def replace_empty_fields(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    for place in Place.objects.all():
        if place.long_description is None:
            place.long_description = ''
            place.save()

        if place.short_description is None:
            place.short_description = ''
            place.save()

class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_alter_image_order'),
    ]

    operations = [
        migrations.RunPython(replace_empty_fields),
    ]
